apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-game-2048
spec:
  tls:
  - hosts:
    - "*.<YOUR_PRODUCTION_DOMAIN_NAME>"
    secretName: <YOUR_PRODUCTION_DOMAIN_NAME>
  rules:
    - host: <YOUR_PRODUCTION_DOMAIN_NAME>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-2048
                port:
                  number: 8080
  ingressClassName: nginx
