apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: game-2048
commonAnnotations:
  provider: kubernetes-sample-apps

resources:
  - ../base

patchesStrategicMerge:
- deployment-staging.yaml
- wildcard-certificate-staging.yaml
- wildcard-host-staging.yaml
- wildcard-issuer-staging.yaml
