---
kind: Service
apiVersion: v1
metadata:
  name: doks-example
spec:
  type: LoadBalancer
  selector:
    app: doks-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doks-example
spec:
  replicas: 2
  selector:
    matchLabels:
      service: doks-example
  template:
    metadata:
      labels:
        service: doks-example
    spec:
      containers:
      - name: nginx
        image: digitalocean/doks-example
        ports:
        - containerPort: 80
          protocol: TCP
