apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo

bases:
  - "../base"

patchesStrategicMerge:
  - cart-service/deployment.yaml
  - checkout-service/deployment.yaml
  - currency-service/deployment.yaml
  - email-service/deployment.yaml
  - frontend/deployment.yaml
  - payment-service/deployment.yaml
  - product-catalog-service/deployment.yaml
  - recommendation-service/deployment.yaml
  - shipping-service/deployment.yaml
