apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-game-2048
spec:
  tls:
  - hosts:
    - "*.bond-0.co"
    secretName: bond-0.co
  rules:
    - host: dev.bond-0.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-2048
                port:
                  number: 8080
  ingressClassName: nginx
